const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const {join}=require('node:path');const cn=require('../src/i18n/zh-CN.json'),tw=require('../src/i18n/zh-TW.json');
module.exports=async({browser,origin,root,env})=>{
 for(const language of ['zh-CN','en','zh-TW']){
  const ctx=await browser.newContext(),ctx2=await browser.newContext();const a=await ctx.newPage(),b=await ctx2.newPage();const tr=k=>(language==='zh-CN'?cn:language==='zh-TW'?tw:{})[k]??k;
  const waitIdle=async p=>{await p.waitForFunction(()=>!document.querySelector('[data-loading]'));};
  await a.goto(origin);await a.getByRole('button',{name:language==='en'?'EN':language==='zh-CN'?'简中':'繁中',exact:true}).click();await a.getByLabel(tr('Display name'),{exact:true}).fill('Demo A');await a.getByRole('button',{name:tr('Create profile'),exact:true}).click();await waitIdle(a);await a.getByRole('button',{name:tr('Create room'),exact:true}).click();await a.getByRole('button',{name:tr('Start session'),exact:true}).waitFor();await waitIdle(a);
  const rid=await a.evaluate(()=>Number(sessionStorage.getItem('echorole-room')));const room=await(await a.request.get(origin+'/api/echorole/rooms/'+rid)).json();assert.equal(room.language,language);
  assert.equal(await a.getByRole('group',{name:'Language',exact:true}).count(),0);
  await b.goto(origin);await b.getByLabel('Display name',{exact:true}).fill('Demo B');await b.getByRole('button',{name:'Create profile',exact:true}).click();await waitIdle(b);await b.getByPlaceholder('Invite code',{exact:true}).fill(room.invite_code);await b.getByRole('button',{name:'Join room',exact:true}).click();await b.getByRole('button',{name:tr('Start session'),exact:true}).waitFor();assert.equal(await b.locator('html').getAttribute('lang'),language);
  await a.getByLabel(tr('Scenario'),{exact:true}).selectOption('workplace_team_deadline_conflict');await a.getByRole('button',{name:tr('Start session'),exact:true}).click();await a.getByRole('heading',{name:tr('Current Situation'),exact:true}).waitFor();await b.getByRole('heading',{name:tr('Current Situation'),exact:true}).waitFor();
  const session=await(await a.request.get(origin+'/api/echorole/rooms/'+rid+'/session')).json();
  const input=a.getByLabel(tr('Shared message'),{exact:true});await input.fill('USER TEXT unchanged');await input.press('Shift+Enter');await input.type('second line');assert.equal(await input.inputValue(),'USER TEXT unchanged\nsecond line');await input.press('Enter');await b.getByText('USER TEXT unchanged\nsecond line',{exact:true}).waitFor();await waitIdle(a);assert.equal(await input.inputValue(),'');assert.equal(await a.locator('[data-message-owner=own]').count(),1);assert.equal(await b.locator('[data-message-owner=other]').count(),1);
  if(language==='zh-CN'){
   if(env.ECHOROLE_TEST_REAL_COACH==='1'){
    await a.getByLabel(tr('Message your Coach'),{exact:true}).fill('Fictional practice: I feel unheard about the deadline. Please suggest one calm opening sentence.');
    await a.getByRole('button',{name:tr('Send reflection'),exact:true}).click();
    try { await a.locator('.coach-reply').first().waitFor({timeout:115000}); } catch (error) { const status=await (await a.request.get(origin+'/api/echorole/sessions/'+session.id+'/coach/requests')).json(); console.log('Coach verification states:',status.map(r=>r.state)); throw error; }
    const reply=await a.locator('.coach-reply').first().innerText();assert(/[\u4e00-\u9fff]/.test(reply));
    assert.equal(await b.locator('.coach-reply').count(),0);await a.reload();await a.locator('.coach-reply').first().waitFor();console.log('PASS: one real Coach request returned Chinese, stayed private and survived reload');
   }

   for(let i=0;i<18;i++)await a.evaluate(async({rid,i})=>{const r=await fetch(`/api/echorole/rooms/${rid}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:crypto.randomUUID(),content:`History ${i}\nsecond line\nthird line`})});if(!r.ok)throw Error('chat fixture failed');},{rid,i});
   await a.getByText('History 17',{exact:false}).waitFor();const region=a.getByRole('region',{name:tr('Shared room messages')});await region.evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll',{bubbles:true}));});await b.getByLabel(tr('Shared message'),{exact:true}).fill('NEW MESSAGE preserve scroll');await b.getByLabel(tr('Shared message'),{exact:true}).press('Enter');await a.getByText('NEW MESSAGE preserve scroll',{exact:true}).waitFor();assert((await region.evaluate(el=>el.scrollTop))<10);
   execFileSync(join(root,'backend/.venv/Scripts/python.exe'),['-c',"import os,sqlite3; c=sqlite3.connect(os.environ['ECHOROLE_DB_PATH']);c.execute('UPDATE sessions SET current_stage=3 WHERE id=?',("+session.id+",));c.commit()"],{cwd:root,env});await a.getByRole('button',{name:tr('Refresh status'),exact:true}).click();await a.getByRole('radio',{name:tr('{0} out of 5 stars').replace('{0}','4'),exact:true}).waitFor({state:'visible'});
   const stars=a.getByRole('radiogroup',{name:tr('Peer rating')});await a.waitForFunction(()=>!document.querySelector('[role=radio]').disabled);assert.equal(await stars.getByRole('radio').count(),5);assert.equal(await stars.locator('[aria-checked=true]').count(),0);await stars.getByRole('radio').nth(3).hover();assert.equal(await stars.locator('svg[fill="currentColor"]').count(),4);await a.getByRole('heading',{name:tr('Peer feedback'),exact:true}).hover();assert.equal(await stars.locator('svg[fill="currentColor"]').count(),0);await stars.getByRole('radio').first().focus();await stars.getByRole('radio').first().press('ArrowRight');await a.getByText(tr('{0} stars — {1} points').replace('{0}','2').replace('{1}','20'),{exact:true}).waitFor();await a.reload();await a.getByRole('radio',{name:tr('{0} out of 5 stars').replace('{0}','2'),checked:true}).waitFor();
  }
  for(const width of [1440,1024,768,375]){await a.setViewportSize({width,height:1000});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(process.env.ECHOROLE_SCREENSHOTS)await a.screenshot({path:join(process.env.ECHOROLE_SCREENSHOTS,`localized-${language}-${width}.png`),fullPage:true});}
  await b.getByRole('button',{name:tr('Leave room'),exact:true}).click();await b.getByRole('group',{name:'Language',exact:true}).waitFor();await a.getByRole('button',{name:tr('Leave room'),exact:true}).click();await a.getByRole('group',{name:'Language',exact:true}).waitFor();await ctx.close();await ctx2.close();console.log('PASS: room language '+language+' create/join/lock/scenario/chat/reload/leave and responsive layouts');
 }
};
